[package]
name = "ruwal"
version = "0.1.0"
authors = ["Al <gLiu962@aucklanduni.ac.nz>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
